# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# GITHUB_TOKEN'a yazma izni veriyoruz
permissions:
  contents: write

# Ne zaman çalışacağı
on:
  schedule:
    # Her 6 saatte bir
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Repo'yu checkout et
      - name: Checkout repository
        uses: actions/checkout@v4

      # Snake'i üret
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: esraozgenc
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Dist klasörünü output branch'ine gönder
      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
